import Head from 'next/head'
import {useRouter} from "next/router";
import {teams} from "../../data";

import styles from '../../styles/Home.module.css'

export default function Create() {


    const router = useRouter();

    const handleSubmit = async (event) => {
        // Stop the form from submitting and refreshing the page.
        event.preventDefault()

        // Get data from the form.
        const data = {
            homeTeamID: event.target.homeTeam.value,
            awayTeamID: event.target.awayTeam.value,
        }

        await router.push(`/game/${event.target.homeTeam.value}/${event.target.awayTeam.value}`);
    }


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Game</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <form onSubmit={handleSubmit}>
                    <fieldset>
                        Home team
                        <select name="homeTeam">
                            {teams.map((team, index) => {
                                return <option value={team.id}>{team.name}</option>
                            })}
                        </select>
                    </fieldset>
                    <fieldset>
                        Away team
                        <select name="awayTeam">
                            {teams.map((team, index) => {
                                return <option value={team.id}>{team.name}</option>
                            })}
                        </select>
                    </fieldset>
                    <input type="submit" />
                </form>
            </main>
        </div>
    )
}
