import Head from 'next/head'
import useSwr from 'swr'
import {useRouter} from "next/router";

const fetcher = (url) => fetch(url).then((res) => res.json())

import styles from '../../styles/Home.module.css'

export default function Create() {
    const {data, error} = useSwr(
        '/api/teams',
        fetcher
    )

    const router = useRouter();

    const handleSubmit = async (event) => {
        // Stop the form from submitting and refreshing the page.
        event.preventDefault()

        // Get data from the form.
        const data = {
            homeTeamID: event.target.homeTeam.value,
            awayTeamID: event.target.awayTeam.value,
        }

        const JSONdata = JSON.stringify(data)

        // Send the form data to our API and get a response.
        const response = await fetch('/api/game', {
            // Body of the request is the JSON data we created above.
            body: JSONdata,

            // Tell the server we're sending JSON.
            headers: {
                'Content-Type': 'application/json',
            },
            // The method is POST because we are sending data.
            method: 'POST',
        })

        // Get the response data from server as JSON.
        // If server returns the name submitted, that means the form works.
        const result = await response.json();
        console.dir(result);
        await router.push(`/game/${result.id}`);
    }

    if (error) return <div>Failed to load teams</div>
    if (!data) return <div>Loading...</div>


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Game</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <form onSubmit={handleSubmit}>
                    <fieldset>
                        Home team
                        <select name="homeTeam">
                            {data.map((team, index) => {
                                return <option value={team.id}>{team.name}</option>
                            })}
                        </select>
                    </fieldset>
                    <fieldset>
                        Away team
                        <select name="awayTeam">
                            {data.map((team, index) => {
                                return <option value={team.id}>{team.name}</option>
                            })}
                        </select>
                    </fieldset>
                    <input type="submit" />
                </form>
            </main>
        </div>
    )
}
